<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bokunorecipe"
 *
 * Auto generated by Extension Builder 2021-11-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Svelte Demo',
    'description' => 'Demo project for svelte integration into TYPO3',
    'category' => 'plugin',
    'author' => 'Markus Ketterer, Matthias Andrasch',
    'author_email' => '4tmestorage@gmail.com',
    'state' => 'alpha',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0-11.5.99',
        ]
    ],
];
