base: "https://live-site.example.com/"
# https://t3planet.de/blog/typo3-context/
baseVariants:
  - base: "https://ddev-typo3-mix-svelte.ddev.site/"
    condition: 'applicationContext == "Development/Local"'
errorHandling: {}
languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
rootPageId: 1
routes: {}
